project:
  type: manuscript

meca-bundle: false

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  acm-pdf: 
    keep-tex: true



