project:
  type: manuscript
  output-dir: docs

manuscript:
  meca-bundle: false

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  acm-pdf: 
    keep-tex: true
    pdf-engine: xelatex
    include-in-header:
      text: |
        \usepackage{newunicodechar}
        \newunicodechar{Î»}{\ensuremath{\lambda}}



