project:
  type: manuscript

execute:
  freeze: auto
  meca-bundle: false

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  acm-pdf: 
    keep-tex: true



