on:
  workflow_dispatch:
  push:
    branches: acm

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
          tinytex: true
          
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2' 
      
      - uses: r-lib/actions/setup-renv@v2
        with:
          profile: 'options(repos=c(CRAN="http://ftp.osuosl.org/pub/cran/"))'
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
