on:
  workflow_dispatch:
  push:
    branches: acm

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1
        
      - name: Ensure OpenSSL is installed
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl
          sudo apt-get install -y ca-certificates

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
          tinytex: true
          
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2' 
      
      - name: Install R packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Function to extract package names from the qmd file
          extract_packages <- function(file_path) {
            content <- readLines(file_path)
            library_calls <- grep("^library\\(|^require\\(", content, value = TRUE)
            packages <- gsub("^library\\(|^require\\(|\\)$", "", library_calls)
            unique(packages)
          }

          # List of packages available in Stan universe
          stan_packages <- c("rstan", "rstanarm", "brms", "cmdstanr", "bayesplot", "shinystan", "loo", "projpred", "posterior")

          # Extract packages from index.qmd
          qmd_file <- "index.qmd"
          if (!file.exists(qmd_file)) {
            stop("index.qmd not found in the current directory")
          }
          packages <- extract_packages(qmd_file)

          # Separate Stan and CRAN packages
          stan_to_install <- intersect(packages, stan_packages)
          cran_to_install <- setdiff(packages, stan_packages)

          # Install Stan packages
          if (length(stan_to_install) > 0) {
            install.packages("remotes")
            remotes::install_github("stan-dev/rstantools")
            sapply(stan_to_install, function(pkg) remotes::install_github(paste0("stan-dev/", pkg)))
          }

          # Install CRAN packages
          if (length(cran_to_install) > 0) {
            install.packages(c("knitr", "rmarkdown", cran_to_install))
          }

          # Print installed packages for debugging
          print("Installed packages:")
          print(installed.packages()[,"Package"])
        shell: Rscript {0}

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
